spring:
    profiles: default
musicBeanz:
    baseURI: http://musicbrainz.org
wikipedia:
    baseURI: https://en.wikipedia.org
coverArtArchive:
    baseURI: http://coverartarchive.org
    
---

spring:
    profiles: integration-test
musicBeanz:
    baseURI: http://localhost:8081
wikipedia:
    baseURI: http://localhost:8082
coverArtArchive:
    baseURI: http://localhost:8083
    