spring:
    profiles: default
musicBeanz:
    baseURI: http://musicbrainz.org
wikipedia:
    baseURI: https://en.wikipedia.org
    
---

spring:
    profiles: integration-test
musicBeanz:
    baseURI: http://localhost:8081
wikipedia:
    baseURI: http://localhost:8082
    