server:
  port: 8100
 
---

spring:
    profiles: default
musicBrainz:
    baseURI: http://musicbrainz.org
wikipedia:
    baseURI: https://en.wikipedia.org
coverArtArchive:
    baseURI: http://coverartarchive.org
    
---

spring:
    profiles: integration-test
musicBrainz:
    baseURI: http://localhost:8101
wikipedia:
    baseURI: http://localhost:8102
coverArtArchive:
    baseURI: http://localhost:8103
    